{
  FrameLayout,
  layout_width="fill",
  layout_height="fill",
  id="背景2";
  background="#ff000000",
  {
    TextureView,
    id="外texture",
    layout_width="fill",
    layout_height="fill",
  },
  {
    LinearLayout,
    layout_width="fill",
    layout_height="fill",
    orientation="vertical";
    id="背景";
    {
      LinearLayout;
      layout_width="fill";
      orientation="horizontal";
      gravity="center";
      --layout_weight="1";
      {
        LinearLayout;
        layout_width="fill";
        orientation="horizontal";
        gravity="center";
        layout_weight="1";
        id="工具箱LinearLayout",
        {
          ImageView,--图片框控件
          layout_weight="1",--重力分配
          layout_width="26dp",--布局宽度
          layout_height="26dp",--布局高度
          src="png/inbox_black.png",--视图路径
          colorFilter=文字,--图片颜色
          id="工具箱ImageView",
          layout_margin="12dp";
        },
      };
      {
        LinearLayout;
        layout_width="fill";
        orientation="horizontal";
        gravity="center";
        layout_weight="1";
        id="闪光灯LinearLayout",
        {
          ImageView,--图片框控件
          layout_weight="1",--重力分配
          layout_width="26dp",--布局宽度
          layout_height="26dp",--布局高度
          src="png/flash_off_black.png",--视图路径
          colorFilter=文字,--图片颜色
          id="闪光灯ImageView",
          layout_margin="12dp";
        },
      };
      {
        LinearLayout;
        layout_width="fill";
        orientation="horizontal";
        gravity="center";
        layout_weight="1";
        id="切换摄像头LinearLayout",
        {
          ImageView,--图片框控件
          layout_weight="1",--重力分配
          layout_width="26dp",--布局宽度
          layout_height="26dp",--布局高度
          src="png/switch_camera_black.png",--视图路径
          colorFilter=文字,--图片颜色
          id="切换摄像头ImageView",
          layout_margin="12dp";
        },
      };
      {
        LinearLayout;
        layout_width="fill";
        orientation="horizontal";
        gravity="center";
        layout_weight="1";
        id="滤镜LinearLayout",
        {
          ImageView,--图片框控件
          layout_weight="1",--重力分配
          layout_width="26dp",--布局宽度
          layout_height="26dp",--布局高度
          src="png/style_black.png",--视图路径
          colorFilter=文字,--图片颜色
          id="滤镜ImageView",
          layout_margin="12dp";
        },
      };
      {
        LinearLayout;
        layout_width="fill";
        orientation="horizontal";
        gravity="center";
        layout_weight="1";
        id="设置LinearLayout",
        {
          ImageView,--图片框控件
          layout_weight="1",--重力分配
          layout_width="26dp",--布局宽度
          layout_height="26dp",--布局高度
          src="png/settings.png",--视图路径
          colorFilter=文字,--图片颜色
          id="设置ImageView",
          layout_margin="12dp";
        },
      };
    };
    {
      FrameLayout,
      layout_width="fill",
      layout_height=activity.width/3*4,
      id="内背景2";
      layout_gravity="center",
      {
        FrameLayout,
        layout_width="fill",
        layout_height=activity.width/3*4,
        id="内背景";
        layout_gravity="center",
        {
          TextureView,
          id="texture",
          layout_width="fill",
          layout_height=activity.width/3*4,
          layout_gravity="center",
        },
        {
          FrameLayout,
          layout_width="fill",
          layout_height="fill",
          id="参考线",
          {
            LinearLayout;
            layout_width="fill",
            layout_height="fill",
            orientation="vertical";
            {
              LinearLayout;
              layout_weight="1";
            };
            {
              Button;
              layout_width="fill";
              -- layout_marginTop=activity.width/3*4/3;
              layout_height="1dp";
              backgroundColor="#FFDCDCDC";
              style="?android:attr/borderlessButtonStyle";
            };
            {
              LinearLayout;
              layout_weight="1";
            };
            {
              Button;
              layout_width="fill";
              --  layout_marginTop=activity.width/3*4/1.5;
              layout_height="1dp";
              backgroundColor="#FFDCDCDC";
              style="?android:attr/borderlessButtonStyle";
            };
            {
              LinearLayout;
              layout_weight="1";
            };
          };
          {
            Button;
            layout_width="1dp";
            layout_marginLeft=activity.width/3;
            layout_height="fill";
            backgroundColor="#FFDCDCDC";
            style="?android:attr/borderlessButtonStyle";
          };
          {
            Button;
            layout_width="1dp";
            layout_marginLeft=activity.width/1.5;
            layout_height="fill";
            backgroundColor="#FFDCDCDC";
            style="?android:attr/borderlessButtonStyle";
          };
        };
        {
          LinearLayout;
          id="对焦点父布局";
          layout_width="72dp";
          layout_height="72dp";
          {
            LinearLayout;
            layout_width="fill";
            layout_height="fill";
            id="对焦点";
          };
        };
        {
          LinearLayout;
          layout_width="fill";
          orientation="vertical";
          id="菜单卡片父布局";
          -- layout_height=activity.width;
          {
            LinearLayout;
            layout_width="fill";
            orientation="vertical";
            --gravity="center";
            layout_weight="1";
            BackgroundColor="#a6000000";
            layout_height=activity.width/3*2,--布局高度
            layout_margin="8dp",
            id="菜单卡片";
            {
              ScrollView;--线性布局
              layout_width='fill';--布局宽度
              layout_height='wrap';--布局高度
              id='scrollView';--布局高度
              {
                LinearLayout;
                layout_width="fill";
                orientation="vertical";
                id="菜单总父布局";
                {
                  LinearLayout;
                  layout_width="fill";
                  orientation="vertical";
                  id="工具箱父布局";
                  {
                    TextView;
                    textColor=强调色;
                    text='模式切换';
                    layout_margin='8dp';
                    layout_marginLeft="18dp";
                    layout_marginTop="18dp";
                  };
                };
                {
                  LinearLayout;
                  layout_width="fill";
                  orientation="vertical";
                  id="滤镜父布局";
                  {
                    TextView;
                    textColor=强调色;
                    text='滤镜';
                    layout_margin='8dp';
                    layout_marginLeft="18dp";
                    layout_marginTop="18dp";
                  };
                };
              };
            };
          };
        };
        {
          LinearLayout;
          layout_width="fill";
          orientation="vertical";
          layout_gravity="center|bottom";
          gravity="center|bottom";
          id="seekBar背景父布局";
          {
            LinearLayout;
            layout_width="fill";
            orientation="horizontal";
            layout_gravity="center|bottom";
            gravity="center";
            id="seekBar背景";
            BackgroundColor="#60000000";
            {
              TextView;
              textColor=文字;
              id='seekBar左';
              layout_margin='12dp';
              layout_marginRight='0';
            };
            {
              SeekBar;
              --hint="输入";
              padding="20dp";
              layout_marginRight="0";
              layout_width="fill";
              layout_gravity="center|bottom",
              id="seekBar";
              layout_weight="1";
            };
            {
              TextView;
              textColor=文字;
              id='seekBar右';
              layout_margin='12dp';
              layout_marginLeft='0';
            };
          };
        };
      };
    };
    {
      FrameLayout;
      layout_width="fill";
      layout_height='fill';--高
      {
        FrameLayout;
        layout_width="fill";
        {
          LinearLayout;
          layout_width="fill";
          orientation="horizontal";
          layout_gravity="center";
          gravity="center";
          id="seekBar背景上";
         -- layout_margin="10dp",
          {
            LinearLayout;
            layout_weight="1";
            orientation="horizontal";
            {
              LinearLayout;
              orientation="horizontal";
              id="切换自动与手动LinearLayout";
              BackgroundColor="#26FFFFFF";
              layout_marginLeft="10dp",
              {
                FrameLayout;
                id="自动LinearLayout",
                layout_height='fill';
                layout_width='36dp';--宽度
                layout_height='36dp';--高
                {
                  FrameLayout;
                  id="自动LinearLayout2父布局",
                  layout_height='fill';
                  layout_width='fill';--宽度
                  {
                    FrameLayout;
                    id="自动LinearLayout2",
                    layout_height='fill';
                    layout_width='fill';--宽度
                    BackgroundColor="#4CFFFFFF";
                  };
                };
                {
                  TextView;
                  textColor=文字;
                  text='A';
                  id='自动TextView';
                  textSize="16sp";
                  layout_gravity="center";
                };
              };
              {
                FrameLayout;
                id="手动LinearLayout",
                layout_height='fill';
                layout_width='36dp';--宽度
                layout_height='36dp';--高
                --layout_marginRight="10dp",
                {
                  FrameLayout;
                  id="手动LinearLayout2父布局",
                  layout_height='fill';
                  layout_width='fill';--宽度
                  {
                    FrameLayout;
                    id="手动LinearLayout2",
                    layout_height='fill';
                    layout_width='fill';--宽度
                    BackgroundColor="#4CFFFFFF";
                  };
                };
                {
                  TextView;
                  textColor=文字;
                  text='M';
                  id='手动TextView';
                  textSize="16sp";
                  layout_gravity="center";
                };
              };
            };
          };
          {
            TextView;
            textColor=文字;
            id='当前参数';
            textSize="16sp";
            layout_marginRight="10dp",
            layout_height='36dp';
            gravity="right|center";
          };
          {
            LinearLayout;
            orientation="horizontal";
            id="加锁LinearLayout",
            gravity="center";
            {
              ImageView,--图片框控件
              layout_width="26dp",--布局宽度
              layout_height="26dp",--布局高度
              src="png/lock_black.png",--视图路径
              layout_margin="10dp",
              colorFilter=文字,--图片颜色
              id="加锁ImageView",
              layout_gravity="center";
            },
          };
        };
        {
          LinearLayout;
          layout_width="fill";
          id="底部菜单2";
          layout_margin="10dp",
          {
            LinearLayout;
            layout_width="fill";
            orientation="horizontal";
            layout_gravity="left";
            gravity="left|center";
            id="底部菜单";
            background="#ff000000",
            {
              LinearLayout;
              layout_width="fill";
              orientation="horizontal";
              layout_gravity="left";
              gravity="left|center";
              layout_weight="1";
              {
                LinearLayout;
                orientation="horizontal";
                id="拍照和录像LinearLayout";
                BackgroundColor="#26FFFFFF";
                {
                  FrameLayout;
                  id="拍照LinearLayout",
                  layout_height='fill';
                  layout_width='36dp';--宽度
                  layout_height='36dp';--高
                  layout_marginRight="10dp",
                  {
                    FrameLayout;
                    id="拍照LinearLayout2父布局",
                    layout_height='fill';
                    layout_width='fill';--宽度
                    {
                      FrameLayout;
                      id="拍照LinearLayout2",
                      layout_height='fill';
                      layout_width='fill';--宽度
                      BackgroundColor="#4CFFFFFF";
                    };
                  };
                  {
                    ImageView,--图片框控件
                    layout_width="26dp",--布局宽度
                    layout_height="26dp",--布局高度
                    src="png/photo_camera_black.png",--视图路径
                    colorFilter=文字,--图片颜色
                    id="拍照ImageView",
                    layout_gravity="center";
                  },
                };
                {
                  FrameLayout;
                  id="录像LinearLayout",
                  layout_height='fill';
                  layout_width='36dp';--宽度
                  layout_height='36dp';--高
                  --layout_marginRight="10dp",
                  {
                    FrameLayout;
                    id="录像LinearLayout2父布局",
                    layout_height='fill';
                    layout_width='fill';--宽度
                    {
                      FrameLayout;
                      id="录像LinearLayout2",
                      layout_height='fill';
                      layout_width='fill';--宽度
                      BackgroundColor="#4CFFFFFF";
                    };
                  };
                  {
                    ImageView,--图片框控件
                    layout_width="26dp",--布局宽度
                    layout_height="26dp",--布局高度
                    src="png/videocam_black.png",--视图路径
                    colorFilter=文字,--图片颜色
                    id="录像mageView",
                    layout_gravity="center";
                  },
                };
              };
            };
            {
              LinearLayout;
              orientation="horizontal";
              layout_gravity="right";
              gravity="right|center";
              background="#ff000000",
              {
                TextView;
                textColor=文字;
                text='A';
                id='切换是否手动控制';
                textSize="16sp";
                -- layout_marginRight="10dp",
                layout_width='36dp';--宽度
                layout_height='36dp';--高
                gravity="center";
              };
              {
                LinearLayout;
                orientation="horizontal";
                gravity="center";
                id="降噪LinearLayout",
                layout_height='fill';
                layout_width='36dp';--宽度
                layout_height='36dp';--高
                -- layout_marginRight="10dp",
                {
                  ImageView,--图片框控件
                  layout_weight="1",--重力分配
                  layout_width="26dp",--布局宽度
                  layout_height="26dp",--布局高度
                  src="png/gradient_black.png",--视图路径
                  colorFilter=文字,--图片颜色
                  id="降噪ImageView",
                },
              };
              {
                TextView;
                textColor=文字;
                text='RAW';
                id='格式';
                textSize="16sp";
                paddingRight="10dp",
                paddingLeft="10dp",
                layout_height='36dp';
                gravity="right|center";
              };
              {
                CardView;--卡片控件
                CardElevation='8dp';--卡片阴影
                --adjustViewBounds=true,
                layout_width='36dp';--卡片宽度
                layout_height='36dp';--卡片高
                layout_gravity="right";
                radius='18dp';--卡片圆角
                CardBackgroundColor="#f0000000";--卡片背景颜色--#F17F42
                id='最新照片CardView';
                {
                  LinearLayout;
                  layout_width="fill";
                  layout_height="fill";
                  id="最新照片父布局";
                  gravity="center";
                  {
                    ImageView;
                    id='最新照片';
                    layout_width="36dp";
                    layout_height="36dp";
                    scaleType='fitXY';
                  };
                };
              };
            };
          };
        };
      };
      {
        FrameLayout;
        layout_width='72dp';--宽度
        layout_height='72dp';--高
        layout_margin="10dp",
        id="tv0";
        layout_gravity="center";
        backgroundColor="#FFDCDCDC";
        {
          FrameLayout;
          layout_width='72dp';--宽度
          layout_height='72dp';--高
          -- layout_margin="10dp",
          id="tv";
          backgroundColor="#FFDCDCDC";
          {
            LinearLayout;
            layout_width='36dp';--宽度
            layout_height='36dp';--高
            -- layout_margin="10dp",
            id="录像停止按钮";
            gravity="center";
            layout_gravity="center";
          };
          {
            TextView;
            -- colorFilter=0xFFffffff;
            textColor="#ff000000";
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="拍照按钮显示文本";
            textSize="26sp";
          };
        };
      };
      {
        LinearLayout;
        layout_width="fill";
        orientation="horizontal";
        layout_gravity="center|bottom";
        gravity="center|bottom";
        {
          LinearLayout;
          gravity="center";
          layout_weight="1";
          layout_width="fill",--布局宽度
          layout_height="60dp",--布局高度
          orientation="vertical";
          id="曝光时间";
          {
            TextView;
            -- colorFilter=0xFFffffff;
            text="曝光时间";
            textColor=文字;
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="曝光时间标题";
            textSize="12sp";
          };
          {
            TextView;
            -- colorFilter=0xFFffffff;
            text="1/80";
            textColor=文字123;
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="曝光时间当前状态";
            textSize="12sp";
          };
        };
        {
          LinearLayout;
          gravity="center";
          layout_weight="1";
          layout_width="fill",--布局宽度
          layout_height="60dp",--布局高度
          orientation="vertical";
          id="ISO";
          {
            TextView;
            -- colorFilter=0xFFffffff;
            text="ISO";
            textColor=文字;
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="ISO标题";
            textSize="12sp";
          };
          {
            TextView;
            -- colorFilter=0xFFffffff;
            text="100";
            textColor=文字123;
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="ISO当前状态";
            textSize="12sp";
          };
        };
        {
          LinearLayout;
          gravity="center";
          layout_width="92dp",--布局宽度
          layout_height="60dp",--布局高度
          orientation="vertical";
        };
        {
          LinearLayout;
          gravity="center";
          layout_weight="1";
          layout_width="fill",--布局宽度
          layout_height="60dp",--布局高度
          orientation="vertical";
          id="曝光补偿";
          {
            TextView;
            -- colorFilter=0xFFffffff;
            text="曝光补偿";
            textColor=文字;
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="曝光补偿标题";
            textSize="12sp";
          };
          {
            TextView;
            -- colorFilter=0xFFffffff;
            text="0";
            textColor=文字123;
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="曝光补偿当前状态";
            textSize="12sp";
          };
        };
        {
          LinearLayout;
          gravity="center";
          layout_weight="1";
          layout_width="fill",--布局宽度
          layout_height="60dp",--布局高度
          orientation="vertical";
          id="焦距";
          {
            TextView;
            -- colorFilter=0xFFffffff;
            text="焦距";
            textColor=文字;
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="焦距标题";
            textSize="12sp";
          };
          {
            TextView;
            -- colorFilter=0xFFffffff;
            text="0";
            textColor=文字123;
            layout_gravity="center";
            gravity="center";
            layout_width="fill",--布局宽度
            id="焦距当前状态";
            textSize="12sp";
          };
        };
      };
    };
  };
}
